---
title: "PNC Compute Functional Connectivity Metrics"
author: "Audrey Luo"
output: html_document
---


```{r setup, include=FALSE}

library(dplyr)
source("/cbica/projects/network_replication/adapted_Rscripts/computeConnectivityMetrics.R")
dataset="PNC"

knitr::opts_chunk$set(include = FALSE, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE) 
```


```{r loadParticipants}
# load participants
 
participants <- read.csv("/cbica/projects/network_replication/input/PNC/sample_selection/PNC_demographics_finalsample_restOnly_20230103.csv")
participants <- paste0("sub-", participants$rbcid)

 
```



```{r computeGBC}
# make output dfs: 
## GBC.subxparcel.matrix.glasser, GBC.subxparcel.matrix.gordon, GBC.subxparcel.matrix.schaefer200x7, GBC.subxparcel.matrix.schaefer400x7
atlases <- c("glasser", "gordon", "schaefer200", "schaefer400")
metric = "GBC"

for(i in c(1:length(atlases))){
  df_name <- paste0(metric, ".subxparcel.matrix.", atlases[i])
  assign(df_name, make_output_dfs(participants, atlases[i]))
}


# compute GBC
for(sub in c(1:length(participants))){
  for(i in c(1:length(atlases))){
    subjectID=as.character(participants[sub])
    id.data <- computeGBC_restOnly(subjectID, atlases[i], dataset)
    dataname <- sprintf("%s.%s.%s", metric, "subxparcel.matrix", atlases[i]) 
    df_toUpdate <- get(dataname)
    df_toUpdate[sub,] <- cbind(subjectID, t(id.data)) #update the name of the df every iteration to GBC.subxparcel.matrix.[atlas]
    assign(dataname, df_toUpdate)  
    print(paste(sub, "/", length(participants), "-", subjectID, atlases[i]))
  }
}

write.csv(GBC.subxparcel.matrix.glasser, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/GBC/GBC_subxparcel_matrix_glasser.csv", dataset), row.names=F, quote=F)
write.csv(GBC.subxparcel.matrix.gordon, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/GBC/GBC_subxparcel_matrix_gordon.csv", dataset), row.names=F, quote=F)
write.csv(GBC.subxparcel.matrix.schaefer200, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/GBC/GBC_subxparcel_matrix_schaefer200.csv", dataset), row.names=F, quote=F)
write.csv(GBC.subxparcel.matrix.schaefer400, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/GBC/GBC_subxparcel_matrix_schaefer400.csv", dataset), row.names=F, quote=F)
   
```



```{r computeBNC}
   
# make output dfs: 
## BNC.subxparcel.matrix.gordon, BNC.subxparcel.matrix.schaefer200x7, BNC.subxparcel.matrix.schaefer400x7, BNC.subxparcel.matrix.schaefer200x17, BNC.subxparcel.matrix.schaefer400x17
atlases <- c("gordon", "schaefer200x7", "schaefer200x17", "schaefer400x7", "schaefer400x17")
 
metric = "BNC"

for(i in c(1:length(atlases))){
  df_name <- paste0(metric, ".subxparcel.matrix.", atlases[i])
  assign(df_name, make_output_dfs(participants, atlases[i]))
}


# compute BNC
for(sub in c(1:length(participants))){
  for(i in c(1:length(atlases))){
    subjectID=as.character(participants[sub])
    print(paste(subjectID, atlases[i], metric, dataset))
    id.data <- computeBNC_WNC_restOnly(subjectID, atlases[i], metric, dataset)
    
    dataname <- sprintf("%s.%s.%s", metric, "subxparcel.matrix", atlases[i]) 
    df_toUpdate <- get(dataname)
    df_toUpdate[sub,] <- cbind(subjectID, t(id.data)) #update the name of the df every iteration to BNC.subxparcel.matrix.[atlas]
    assign(dataname, df_toUpdate)  
    print(paste(sub, "/", length(participants), "-", subjectID, atlases[i]))
  }
}


write.csv(BNC.subxparcel.matrix.gordon, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/BNC/BNC_subxparcel_matrix_gordon.csv", dataset), row.names=F, quote=F)
write.csv(BNC.subxparcel.matrix.schaefer200x7, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/BNC/BNC_subxparcel_matrix_schaefer200x7.csv", dataset), row.names=F, quote=F)
write.csv(BNC.subxparcel.matrix.schaefer400x7, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/BNC/BNC_subxparcel_matrix_schaefer400x7.csv", dataset), row.names=F, quote=F)
write.csv(BNC.subxparcel.matrix.schaefer200x17, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/BNC/BNC_subxparcel_matrix_schaefer200x17.csv", dataset), row.names=F, quote=F)
write.csv(BNC.subxparcel.matrix.schaefer400x17, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/BNC/BNC_subxparcel_matrix_schaefer400x17.csv", dataset), row.names=F, quote=F)
 

```
 
 

```{r computeWNC}

# make output dfs: 
## WNC.subxparcel.matrix.gordon, WNC.subxparcel.matrix.schaefer200x7, WNC.subxparcel.matrix.schaefer400x7
atlases <- c("gordon", "schaefer200x7", "schaefer200x17", "schaefer400x7", "schaefer400x17")
 
metric = "WNC"

for(i in c(1:length(atlases))){
  df_name <- paste0(metric, ".subxparcel.matrix.", atlases[i])
  assign(df_name, make_output_dfs(participants, atlases[i]))
}


# compute BNC
for(sub in c(1:length(participants))){
  for(i in c(1:length(atlases))){
    subjectID=as.character(participants[sub])
    print(paste(subjectID, atlases[i], metric, dataset))
    id.data <- computeBNC_WNC_restOnly(subjectID, atlases[i], metric, dataset)
    
    dataname <- sprintf("%s.%s.%s", metric, "subxparcel.matrix", atlases[i]) 
    df_toUpdate <- get(dataname)
    df_toUpdate[sub,] <- cbind(subjectID, t(id.data)) #update the name of the df every iteration to BNC.subxparcel.matrix.[atlas]
    assign(dataname, df_toUpdate)  
    print(paste(sub, "/", length(participants), "-", subjectID, atlases[i]))
  }
}



write.csv(WNC.subxparcel.matrix.gordon, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/WNC/WNC_subxparcel_matrix_gordon.csv", dataset), row.names=F, quote=F)
write.csv(WNC.subxparcel.matrix.schaefer200x7, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/WNC/WNC_subxparcel_matrix_schaefer200x7.csv", dataset), row.names=F, quote=F)
write.csv(WNC.subxparcel.matrix.schaefer400x7, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/WNC/WNC_subxparcel_matrix_schaefer400x7.csv", dataset), row.names=F, quote=F)
write.csv(WNC.subxparcel.matrix.schaefer200x17, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/WNC/WNC_subxparcel_matrix_schaefer200x17.csv", dataset), row.names=F, quote=F)
write.csv(WNC.subxparcel.matrix.schaefer400x17, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/WNC/WNC_subxparcel_matrix_schaefer400x17.csv", dataset), row.names=F, quote=F)

```


# Extract edge-level data (parcel-to-parcel connectivity)
```{r edge_level_dfs}

# make a dataframe in which rows are subjects, and columns are the names of the edges (parcel1_to_parcel2)
# the entries represent the parcel-by-parcel correlation
 
# for each subject, turn the connectivity matrix into a vector

extractEdge.gordon <- lapply(participants, extractParcel2ParcelConn, "gordon", dataset)
extractEdge.glasser <- lapply(participants, extractParcel2ParcelConn, "glasser", dataset)
extractEdge.schaefer200x7 <- lapply(participants, extractParcel2ParcelConn, "schaefer200x7", dataset)
extractEdge.schaefer200x17 <- lapply(participants, extractParcel2ParcelConn, "schaefer200x17", dataset)
extractEdge.schaefer400x7 <- lapply(participants, extractParcel2ParcelConn, "schaefer400x7", dataset)
extractEdge.schaefer400x17 <- lapply(participants, extractParcel2ParcelConn, "schaefer400x17", dataset)


# for other atlases  
atlases <- c("glasser", "gordon", "schaefer200x7", "schaefer200x17", "schaefer400x7", "schaefer400x17")
 
for(i in c(1:length(atlases))){
  extractEdge <- get(paste0("extractEdge.", atlases[i]))
  names(extractEdge) <- participants 
  columns_extractEdge <- bind_rows(extractEdge) # turn list into a dataframe
  subxedge <- as.data.frame(t(columns_extractEdge)) # transpose dataframe
  
  edge <- read.csv(sprintf("/cbica/projects/network_replication/atlases/edge/%1$s_edge.csv", atlases[i]))
  edge <- edge[,2]
  names(subxedge) <- edge # columns = names of edges
  
  subxedge <- subxedge %>% mutate(subject = rownames(subxedge))
  subxedge <- subxedge %>% relocate(subject)
  rownames(subxedge) <- NULL
  
  saveRDS(subxedge, sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analysis/edge/subxedge_%2$s.RData", dataset, atlases[i])) 
  print(atlases[i])
} 
 
 
```





