---
title: "PNC fit GAMs"
author: "Audrey Luo"
date: "2023-01-04"
output: html_document
---

```{r setup, include=FALSE}

library(dplyr)
source("/cbica/projects/network_replication/Rscripts/functions/main_analyses/GAM_functions.R") # same functions as used for main analysis
source("/cbica/projects/network_replication/Rscripts/functions/sensitivity_analyses/fitGAMs_restOnly.R") 
 
dataset = "PNC"
knitr::opts_chunk$set(include = FALSE, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE) 
  
```

 
# make connectivityMetric-demographics .csv's
```{r connMetric_demographics, include=FALSE}

demographics <- read.csv("/cbica/projects/network_replication/input/PNC/sample_selection/PNC_demographics_finalsample_restOnly_20230629.csv")
demographics <- demographics %>% rename(subject=sub) 
demographics$age <- demographics$ageAtScan1/12
demographics <- demographics[,c(which(names(demographics) == "subject"), which(names(demographics) == "sex"), which(names(demographics)=="age"), which(names(demographics) =="meanFD_avgSes"))] 


## creates GBC.schaefer200.PNC 
GBC.schaefer200.PNC <- make_connMetricsDemog("schaefer200", "GBC", demographics, "subject", dataset)
 
```


 


# load connectivityMetric-demographics .csv's
```{r load_connectivity, include=TRUE}  
GBC.schaefer200.PNC <- read.csv(sprintf("/cbica/projects/network_replication/output/%1$s/sensitivity_analyses/GBC/GBCschaefer200_demographics_finalsample.csv", dataset)) 
names(GBC.schaefer200.PNC) <- gsub('X17Networks', "Networks", names(GBC.schaefer200.PNC))
 
GBC.schaefer200.PNC$sex <- as.factor(GBC.schaefer200.PNC$sex)
 
 
```

 
# load parcel labels and edges 
```{r}
# load parcel labels 
schaefer200x17.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/schaefer200x17_regionlist_final.csv")
```  


# Fit GAMs
```{r}
# GBC GAMs
gam.GBC.age.schaefer200 <- fitGAMs(schaefer200x17.parcel.labels, "GBC", "schaefer200", "", dataset)
```




# Estimate GAM smooths based on model-predicted data and save out predicted y data** 
```{r}
# GBC GAMs 
gam.GBC.smooths.schaefer200 <- estimate_GAMsmooths(schaefer200x17.parcel.labels, "GBC", "schaefer200", "", dataset)
```



