---
title: "Fit GAMs"
author: "Audrey Luo"
date: "2023-11-15"
output: html_document
---
 

```{r setup, include=FALSE}

library(dplyr)
source("/cbica/projects/network_replication/revisions/code/utils/GAM_functions_revisions.R")
source("/cbica/projects/network_replication/revisions/code/utils/fitGAMs_revisions.R")  
dataset = "PNC"
knitr::opts_chunk$set(include = FALSE, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE) 
```
 
 
# make connectivityMetric-demographics .csv's
```{r connMetric_demographics, include=FALSE}

demographics <- read.csv("/cbica/projects/network_replication/input/PNC/sample_selection/PNC_demographics_finalsample_20230629.csv")
demographics <- demographics %>% dplyr::rename(subject=sub)
 
 
# GBC - combine GBC with demographics
GBC.schaefer200_thresholded <- make_connMetricsDemog("schaefer200", "GBC", demographics, "subject", dataset, "thresholded")
GBC.schaefer200_absvalue <- make_connMetricsDemog("schaefer200", "GBC", demographics, "subject", dataset, "absvalue")

GBC.schaefer200_thresholded$sex <- as.factor(GBC.schaefer200_thresholded$sex)
GBC.schaefer200_absvalue$sex <- as.factor(GBC.schaefer200_absvalue$sex)
```
  
 
# load parcel labels 
```{r}
# load parcel labels 
schaefer200x7.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/schaefer200x7_regionlist_final.csv")
 
```  


# Fit GAMs for GBC 
```{r}
 
# GBC GAMs 
gam.GBC.age.thresholded <- fitGAMs(schaefer200x7.parcel.labels, "GBC", "schaefer200", "", dataset_name = dataset, conn_type = "thresholded")
gam.GBC.age.absvalue <- fitGAMs(schaefer200x7.parcel.labels, "GBC", "schaefer200", "", dataset_name = dataset, conn_type = "absvalue")
    
```

  

