---
title: "NKI QC"
author: "Audrey Luo"
date: '2022-07-15'
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)
library(magrittr)
library(reshape)
library(reshape2)
library(MASS)
library(stargazer)
```


```{r qc_setup, include=FALSE, eval=FALSE}
#load one QC file to look at
# getting filenames of all the relevant xcp outputs - sub-*/ses-*/func/*rest*fsLR*qc*.csv. Just for record keeping!
NKI_xcp_files <- read.table("/cbica/projects/network_replication/NKI/NKI_xcp_filenames.txt")
NKI_xcp_files$V1 <- gsub("@", "", NKI_xcp_files$V1)
NKI_xcp_filePaths <- paste0("/cbica/projects/RBC/RBC_DERIVATIVES/NKI/nki_xcp/", NKI_xcp_files$V1)
write.table(NKI_xcp_filePaths, "/cbica/projects/network_replication/NKI/NKI_xcp_filenames.txt")
 
# load collated NKI outputs
collated_NKI.xcp_temp <- read.csv('/cbica/projects/network_replication/NKI/collated_NKI_xcp.csv') #collated_NKI_xcp.csv made from `cat /cbica/projects/RBC/RBC_DERIVATIVES/NKI/nki_xcp/sub-*/ses-*/func/*rest*fsLR*qc*.csv`
toDelete <- seq(0, nrow(collated_NKI.xcp_temp), 2)
collated_NKI.xcp_temp <- collated_NKI.xcp_temp[-toDelete,]

# add binary column indicating FD >0.3 (exclude)
collated_NKI.xcp_temp <- collated_NKI.xcp_temp %>% mutate(Exclude = ifelse(meanFD>0.3, 1, 0))

# append T1 QA? not sure how to since they have multiple qc ratings per person
T1_QA <- read.csv("/cbica/projects/network_replication/NKI/T1_QA/EulerNumber_VisualQC_3sites.csv")
 

write.csv(collated_NKI.xcp_temp, "/cbica/projects/network_replication/NKI/collated_NKI_xcpFINAL.csv")
which(T1_QA$rbc_id == collated_NKI.xcp$sub[1])
  
```


```{r table, include=TRUE, results='asis', echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE}
# make table of how many people have BAS1, missing BAS1, more than one BAS1, only have Follow up 

collated_NKI.xcp <- read.csv("/cbica/projects/network_replication/NKI/collated_NKI_xcpFINAL.csv")
 
casted_NKI.xcp <- dcast(collated_NKI.xcp[,c(2:3)], sub~ses)

num_atLeastone_BAS1 <- length(which(casted_NKI.xcp$BAS1 != 0))

num_3_BAS1 <- length(which(casted_NKI.xcp$BAS1 == 3)) #likely because they have CAP, 1400, and 645 acquisitions
num_2_BAS1 <- length(which(casted_NKI.xcp$BAS1 == 2)) #likely missing 1 of CAP, 1400, or 645 acquisitions
num_1_BAS1 <- length(which(casted_NKI.xcp$BAS1 == 1)) #like missing 2 of the above acquisitions
num_missingBAS1 <- length(which(casted_NKI.xcp$BAS1 == 0))
num_missingBAS1_hasBAS2or3 <- 0
num_onlyFLU <- length(which(casted_NKI.xcp$BAS1 == 0 & casted_NKI.xcp$FLU1 >0 | casted_NKI.xcp$FLU2 >0 | casted_NKI.xcp$FLU3 >0))
num_onlyFLU1 <- length(which(casted_NKI.xcp$BAS1 == 0 & casted_NKI.xcp$FLU1 >0 & casted_NKI.xcp$FLU2 == 0 & casted_NKI.xcp$FLU3 == 0))
num_onlyFLU2 <- length(which(casted_NKI.xcp$BAS1 == 0 & casted_NKI.xcp$FLU1 ==0 & casted_NKI.xcp$FLU2 >0 & casted_NKI.xcp$FLU3 == 0))
num_onlyFLU3 <- length(which(casted_NKI.xcp$BAS1 == 0 & casted_NKI.xcp$FLU1 ==0 & casted_NKI.xcp$FLU2 ==0 & casted_NKI.xcp$FLU3 > 0))

row_names <- c("At Least One BAS1", "All 3 BAS1 acq", "2 of 3 BAS1 acq", "1 of 3 BAS1 acq", "Missing BAS1", "Missing BAS1, Has BAS2 or BAS3", "Only FLU's", "Only FLU1", "Only FLU2", "Only FLU3")
row_entries <- c(num_atLeastone_BAS1, num_3_BAS1, num_2_BAS1, num_1_BAS1, num_missingBAS1, num_missingBAS1_hasBAS2or3, num_onlyFLU, num_onlyFLU1, num_onlyFLU2, num_onlyFLU3)
 
library(knitr)
library(kableExtra)

kable(cbind(row_names, row_entries), col.names = c("", "Number of Participants"), caption="Sessions")  %>%
  kable_styling(font_size = 20)
 
```

- how many people with bas 1 + at least 1 flu
- how many people with bas 1 + at least 1 flu + INCLUDED based on QC


timeseries test!
```{r}
test1400 <- read.csv("/cbica/projects/RBC/RBC_DERIVATIVES/NKI/nki_xcp/sub-A00086748/ses-BAS1/func/sub-A00086748_ses-BAS1_task-rest_acq-1400_space-MNI152NLin6Asym_atlas-Gordon_desc-timeseries_res-2_bold.tsv", header=F) # rows = ?, columns = parcels i think
test645 <- read.csv("/cbica/projects/RBC/RBC_DERIVATIVES/NKI/nki_xcp/sub-A00086748/ses-BAS1/func/sub-A00086748_ses-BAS1_task-rest_acq-645_space-MNI152NLin6Asym_atlas-Gordon_desc-timeseries_res-2_bold.tsv", header=F)
testCAP <- read.csv("/cbica/projects/RBC/RBC_DERIVATIVES/NKI/nki_xcp/sub-A00086748/ses-BAS1/func/sub-A00086748_ses-BAS1_task-rest_acq-CAP_space-MNI152NLin6Asym_atlas-Gordon_desc-timeseries_res-2_bold.tsv",  header=F)

#concatenate
concat_test <- rbind(test1400, test645, testCAP)
corr_concat <- data.frame(round(cor(concat_test, use = "complete.obs"), 5))
 
 
#average - i think calculating corr matrix for each time series, then taking the average of the corr matrix? 
corr_test1400 <- data.frame(round(cor(test1400, use = "complete.obs"), 5))
corr_test645 <- data.frame(round(cor(test645, use = "complete.obs"), 5))
corr_testCAP <- data.frame(round(cor(testCAP, use = "complete.obs"), 5))


X <- list(corr_test1400, corr_test645, corr_testCAP)
Y <- do.call(cbind, X)
Y <- array(Y, dim=c(dim(X[[1]]), length(X)))

corr_average <- apply(Y, c(1, 2), mean, na.rm = TRUE)



```


