---
title: "Fit GAMs"
author: "Audrey Luo"
date: "2023-11-15"
output: html_document
---
 

```{r setup, include=FALSE}

library(dplyr)
source("/cbica/projects/network_replication/revisions/code/utils/GAM_functions_revisions.R")
dataset = "HBN"
indir = sprintf("/cbica/projects/network_replication/revisions/output/%1$s/withinbetween/", dataset)

knitr::opts_chunk$set(include = FALSE, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE) 
```
 
 
# make connectivityMetric-demographics .csv's
```{r connMetric_demographics, include=FALSE}

demographics <- read.csv(sprintf("/cbica/projects/network_replication/input/%1$s/sample_selection/%1$s_demographics_finalsample_20230629.csv", dataset))
names(demographics)[c(which(names(demographics) == "sub"))] <- "subject"
demographics <- demographics[,c(which(names(demographics) == "subject"), which(names(demographics) == "sex"), which(names(demographics)=="age"), which(names(demographics) =="meanFD_avgSes"))] 
 

 # load mean connectivity - combine with demographics
subxnetpair.matrix <- read.csv(sprintf("%1$swithinbetween_subxnetpair_matrix_schaefer200x7_orig.csv", indir))

netpair.schaefer200_orig <- merge(subxnetpair.matrix, demographics, by="subject")
netpair.schaefer200_orig$sex <- as.factor(netpair.schaefer200_orig$sex)
 
```
  
 
# extract network-network labels 
```{r}
netpair_labels <- names(subxnetpair.matrix)[c(2:length(names(subxnetpair.matrix)))]
 
```  


# Fit GAMs for GBC 
```{r}
 
# network connectivity GAMs 
gam.age <- matrix(data=NA, nrow=length(netpair_labels), ncol=9) #empty matrix to save gam.fit output to
 
for(row in c(1:length(netpair_labels))){ #for each region
  netpair <- netpair_labels[row] 
  GAM.RESULTS <- gam.fit(measure = "netpair", atlas = "schaefer200", conn_type = "orig", region = netpair, smooth_var = "age", covariates = "sex + meanFD_avgSes") #run the gam.fit function
  gam.age[row,] <- GAM.RESULTS}
gam.age <- as.data.frame(gam.age)
colnames(gam.age) <- c("label","GAM.age.Fvalue","GAM.age.pvalue","GAM.age.AdjRsq","Anova.age.pvalue","age.onsetchange","age.peakchange","maxage.BNC.increase","age.maturation" )
cols = c(2:9)    
gam.age[,cols] = apply(gam.age[,cols], 2, function(x) as.numeric(as.character(x)))
gam.age <- gam.age %>% mutate(significant = (Anova.age.pvalue < 0.05))

write.csv(gam.age, sprintf("%1$s/GAM/GAMresults.withinbetween.age.csv", indir), row.names = F, quote = F)
     
```

   

# Estimate GAM smooths based on model-predicted data and save out predicted y data**   
```{r}
gam.smooths <- matrix(data=NA, ncol=7) #empty matrix to save gam.predsmooth fits to
colnames(gam.smooths) <- c("age","fit","se.fit","selo","sehi","index","label")

for(row in c(1:length(netpair_labels))){ #for each region
  netpair <- netpair_labels[row] 
  GAM.SMOOTH <- gam.predsmooth(measure = "netpair", atlas = "schaefer200", conn_type = "orig", region = netpair, smooth_var = "age", covariates = "sex + meanFD_avgSes") #run the gam.predsmooth function
  
  preddata <- as.data.frame(GAM.SMOOTH[3]) #get predicted.smooth df from function output
  preddata$index <- rep(x=row, 1000) #region index
  preddata$label <- rep(x=GAM.SMOOTH[1], 1000) #label
  gam.smooths <- rbind(gam.smooths, preddata)
  
  
}
gam.smooths <- gam.smooths[-1,] #remove empty initialization row
gam.smooths$label <- as.character(gam.smooths$label)

 
write.csv(gam.smooths, sprintf("%1$s/GAM/GAMsmoothfits.withinbetween.csv", indir), row.names = F, quote = F)

 
```
