---
title: "GBC Developmental Trajectories: PNC (Glasser)"
author: "Valerie Jill Sydnor, adapted by Audrey Luo"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
require(ggplot2)
library(cowplot)
library(cifti)
library(ggseg)
Sys.setenv(RGL_USE_NULL=TRUE)
library(ggsegExtra)
library(ggsegGlasser)
library(ggcorrplot)
library(viridis)
library(scales)
library(stringr)
library(tidyr)


```
  
# load Glasser parcellated S-A axis
```{r}
# load SNR mask 
SNRmask_glasser <- read.csv('/cbica/projects/network_replication/atlases/Masks/SNRmask_glasser360.csv')

# load region list
glasser.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/glasser360_regionlist.csv", header = T) 
names(glasser.parcel.labels) <- c("orig_parcelname", "label")
glasser.parcel.labels[which(SNRmask_glasser == 0),] <- NA # apply SNR mask to parcel names
glasser.parcel.labels <- na.omit(glasser.parcel.labels)

# load parcellated SA axis
glasser_SAaxis_cifti <- read_cifti("/cbica/projects/network_replication/SAaxis/SensorimotorAssociation_Axis_parcellated/SensorimotorAssociation.Axis.Glasser360.pscalar.nii")  

glasser_SAaxis <- as.data.frame(cbind(rank(glasser_SAaxis_cifti$data), names(glasser_SAaxis_cifti$Parcel)))
colnames(glasser_SAaxis) <- c("SA.axis_rank","label")


# apply SNR mask
glasser_SAaxis[which(SNRmask_glasser == 0),] <- NA
glasser_SAaxis <- na.omit(glasser_SAaxis)
```


```{r include=FALSE}
## GAM Results

gam.gbc.age.glasser <- read.csv("/cbica/projects/network_replication/GBC/GAM/GAMresults.GBC.age.glasser.csv")

gam.gbc.age.glasser <- gam.gbc.age.glasser %>% select(-label)
gam.gbc.age.glasser$label <- glasser_SAaxis$label
 

gam.smooths.glasser <- read.csv("/cbica/projects/network_replication/GBC/GAM/GAMsmoothfits.GBC.age.glasser.csv")
gam.smooths.glasser$orig_parcelname <- gam.smooths.glasser$label
 

gam.agepeaks.glasser <- read.csv("/cbica/projects/network_replication/GBC/GAM/GAMpeaks.GBC.age.glasser.csv")
gam.agepeaks.glasser <- gam.agepeaks.glasser %>% select(-label)
gam.agepeaks.glasser$label <- glasser.parcel.labels$label

#levels(as.factor(gam.smooths.glasser$orig_parcelname)) 
 
#gam.gbc.age.gordon <- read.csv("/cbica/projects/network_replication/GBC/GAM/GAMresults.GBC.age.gordon.csv")
#gam.gbc.age.schaefer200 <- read.csv("/cbica/projects/network_replication/GBC/GAM/GAMresults.GBC.age.schaefer200.csv")
#gam.gbc.age.schaefer400 <- read.csv("/cbica/projects/network_replication/GBC/GAM/GAMresults.GBC.age.schaefer400.csv")
```

 
# glasser final Dfs
```{r include=FALSE}
# Combine into Final Dfs

df.list <- list(glasser_SAaxis,gam.gbc.age.glasser)
  
gbc.axis <- Reduce(function(x,y) merge(x,y, all=TRUE, sort=F), df.list) 
gbc.axis$SA.axis_rank <- as.numeric(gbc.axis$SA.axis_rank)
 
```

 
```{r include=FALSE}
  
a <- merge(glasser.parcel.labels, glasser_SAaxis, by="label", sort=F)
gam.smooths.glasser <- left_join(gam.smooths.glasser, a, by = "label")
gam.smooths.glasser$SA.axis_rank <-as.numeric(gam.smooths.glasser$SA.axis_rank) 

gam.agepeaks.glasser <- left_join(gam.agepeaks.glasser, glasser_SAaxis, by="label")
gam.agepeaks.glasser$SA.axis_rank <-as.numeric(gam.agepeaks.glasser$SA.axis_rank) 
```
 
 
 
#Spin Test Parcel Rotation Matrix
```{r eval=FALSE, include=TRUE}
source("/cbica/projects/network_replication/software/rotate.parcellation.R")
source("/cbica/projects/network_replication/software/perm.sphere.p.R")

glasser.coords <- read.csv("/cbica/projects/network_replication/software/rotate_parcellation/glasser_spherical_coords.csv", header=F) #coordinates of glasser parcel centroids on the freesurfer sphere

## perm.id.full <- rotate.parcellation(coord.l = as.matrix(glasser.coords[1:180,]), coord.r = as.matrix(glasser.coords[181:360,]), nrot = 10000) #rotate the glasser.coords parcellation 10,000 times on the freesurfer sphere to generate spatial nulls for spin-based permutation significance testing 

 
## saveRDS(perm.id.full, "/cbica/projects/network_replication/software/rotate_parcellation/glasser.coords_sphericalrotations_N10k.rds")

perm.id.full <- readRDS("/cbica/projects/network_replication/software/rotate_parcellation/glasser.coords_sphericalrotations_N10k.rds")

 
```


#create df.dev.spin formatted for spatial permutation testing
```{r}
# need to reintroduced the parcels removed by SNRmask as NA's

glasser.parcel.labels_noMask <- read.csv("/cbica/projects/network_replication/atlases/parcellations/glasser360_regionlist.csv", header = T) 
names(glasser.parcel.labels_noMask) <- c("orig_parcelname", "label")
glasser.parcel.labels_noMask
setdiff(gbc.axis$label, glasser.parcel.labels_noMask$label)

glasser.parcel.labels_noMask$label[which(!glasser.parcel.labels_noMask$label %in% gbc.axis$label)] # names of removed parcels


# need to go through parcel.labels and see which are in gbc.axis label
# then for the ones that aren't in gbc.axis$label, insert parcel.labels[row_of_missing_label] into gbc.axis, and have the rest of the row be NA
# r = the row index -- indices of SNR removed parcels
# newrow = content of inserted row -- c('name of parcel', NA, NA, NA etc)
# existingDF = gbc.axis
insertRow <- function(r, existingDF, orig.parcel.labels) {
  newrow <- c(paste0(orig.parcel.labels[r]), rep(NA, 10)) # format data for spin tests by assigning NA to low SNR parcels, treating them like the medial wall
  existingDF[seq(r+1,nrow(existingDF)+1),] <- existingDF[seq(r,nrow(existingDF)),]
  existingDF[r,] <- newrow
  existingDF
}

  
r <- which(!glasser.parcel.labels_noMask$label %in% gbc.axis$label) # indices of removed parcels
existingDF <- gbc.axis  
 
for(i in c(1:length(r))){
   existingDF <- insertRow(r[i], existingDF, glasser.parcel.labels_noMask$label)
}

   
df.dev.spin <- rbind(existingDF[181:360,], existingDF[1:180,]) #format df as left hemisphere -> right hemisphere for spin tests
SNRmask_glasser_LtoR <- c(SNRmask_glasser$SNR.mask[181:360], SNRmask_glasser$SNR.mask[1:180])
df.dev.spin <- cbind(df.dev.spin, SNRmask_glasser_LtoR)
 
```


# GBC Developmental Effects

## Number of significant parcels (FDR corrected)

```{r echo=FALSE}
gbc.axis$Anova.age.pvalue.fdr <- p.adjust(gbc.axis$Anova.age.pvalue, method=c("fdr"))
cat(sprintf("There are %s/%s significant parcels", sum(gbc.axis$Anova.age.pvalue.fdr < 0.05), nrow(gbc.axis)))

gbc.axis$significant.fdr <- gbc.axis$Anova.age.pvalue.fdr < 0.05
gbc.axis$significant.fdr[gbc.axis$significant.fdr == TRUE] <- 1
gbc.axis$significant.fdr[gbc.axis$significant.fdr == FALSE] <- 0
 
```

# i can't get  this to work
```{r, echo=F, include=F}
plot(glasser, show.legend = FALSE)
ggplot() + geom_brain(data = gbc.axis, atlas = glasser, aes(fill=as.factor(significant.fdr)), show.legend = NA) +scale_fill_discrete(name = "significant.fdr", labels = c("Not Sig","Sig")) 

 ggseg(.data = gbc.axis, atlas = "glasser", mapping=aes(fill=significant.fdr), position = c("stacked")) + theme_void() + scale_fill_discrete(name = "significant.fdr", labels = c("Not Sig","Sig")) # Error: Must request at least one colour from a hue palette.


 ggseg(gbc.axis, atlas = "glasser", mapping=aes(fill=significant.fdr), position = "stacked") + scale_fill_gradientn(colours= c("#053061", "#67001F")) + theme_void()
     
```

## Age Effect by S-A Axis position

```{r}
cor.test(gbc.axis$GAM.age.AdjRsq, as.numeric(gbc.axis$SA.axis_rank), method=c("spearman"), exact=F)
cor(as.numeric(df.dev.spin$GAM.age.AdjRsq), as.numeric(df.dev.spin$SA.axis_rank),method="spearman", use="complete.obs")

perm.sphere.p(as.numeric(df.dev.spin$GAM.age.AdjRsq), as.numeric(df.dev.spin$SA.axis_rank), perm.id.full, corr.type='spearman')
```

```{r, echo=F}
library(ggpubr)
gbc.axis <- gbc.axis %>% mutate(SA.axis_rank_signif = ifelse(significant.fdr == 1, SA.axis_rank, NA))

# included all datapoints
r_text <- expression(paste(italic("r"), "= -0.62, ", italic(p[spin]), "< 0.0001"))

(glasser_SA.AgeEffect <- ggplot(gbc.axis, aes(x=SA.axis_rank, y=GAM.age.AdjRsq, fill = SA.axis_rank_signif)) + geom_point(color = "white", shape = 21, size=2) +
scale_fill_gradient2(low="#6f1282",high = "goldenrod1",, mid = "#EBDAFF", midpoint = median(gbc.axis$SA.axis_rank), na.value="gray") +
labs(fill = "SA Axis Rank", x="\nSensorimotor-Association Axis Rank\n", y=expression(paste("Age Effect (Delta Adj", " R"^2, ")"))) +
geom_smooth(data = gbc.axis, method='lm', se=TRUE, fill=alpha(c("gray70"),.9), col="black") +
theme(
axis.title.x=element_text(size=12, color = "black"),
axis.title.y=element_text(size=12, color = "black"),
axis.line = element_line(color = "black"),
axis.text=element_text(size=12, color = "black"),
panel.background=element_blank(),
legend.position = "right") +
annotate(geom="text", x=240, y=0.05, label=r_text, color="black"))
#ggsave(glasser_SA.AgeEffect, file="/cbica/projects/network_replication/adapted_Rscripts/Figures/Glasser/GBC/glasser_SA.AgeEffect.pdf", width = 5, height=4, dpi=300)



# excluded the non-significant FDR corrected data points to calculate the correlation
signif_gbc.axis <- gbc.axis[which(gbc.axis$significant.fdr ==1),] 
 

## SA axis average rank vs. age effect
(glasser_SA.AgeEffect <- ggplot(gbc.axis, aes(x=SA.axis_rank, y=GAM.age.AdjRsq, fill = SA.axis_rank_signif)) + geom_point(color = "white", shape = 21, size=2) +
scale_fill_gradient2(low="#6f1282",high = "goldenrod1",, mid = "#EBDAFF", midpoint = median(gbc.axis$SA.axis_rank), na.value="gray") +
labs(fill = "SA Axis Rank", x="\nSensorimotor-Association Axis Rank\n", y=expression(paste("Age Effect (Delta Adj", " R"^2, ")"))) +
geom_smooth(data = signif_gbc.axis, method='lm', se=TRUE, fill=alpha(c("gray70"),.9), col="black") +
theme(
axis.title.x=element_text(size=12, color = "black"),
axis.title.y=element_text(size=12, color = "black"),
axis.line = element_line(color = "black"),
axis.text=element_text(size=12, color = "black"),
panel.background=element_blank(),
legend.position = "right") +
annotate(geom="text", x=120, y=0.05, label="R = -0.41, p < 2.2e-16 ", color="black"))
 
 
 
```



## GBC Developmental Trajectories

```{r}
class(gam.smooths.glasser$SA.axis_rank)
# seems like transmodal areas have greater GBC and seem to increase with age, while unimodal areas have smaller GBC and increase or stays the same with age
(glasser_predGBC <- ggplot(gam.smooths.glasser,aes(age,fit,group=index)) + 
  geom_line(data = gam.smooths.glasser, size=.8, alpha = .6, aes(color=SA.axis_rank)) + scale_color_gradient2(low="#6f1282",high = "goldenrod1", mid = "#EBDAFF", midpoint = median(gbc.axis$SA.axis_rank)) + 
  labs(color = "SA Axis Rank",
       x="Age", 
       y="Predicted Global Brain Connectivity") +
  theme(
axis.title.x=element_text(size=12, color = "black"),
axis.title.y=element_text(size=12, color = "black"),
axis.line = element_line(color = "black"),
axis.text=element_text(size=12, color = "black"),
panel.background=element_blank(),
legend.position = "bottom") + coord_cartesian(expand = FALSE, xlim = c(8, 23)))
 
#ggsave(glasser_predGBC, file="/cbica/projects/network_replication/adapted_Rscripts/Figures/Glasser/GBC/glasser_predGBC.pdf", width = 4, height=4, dpi=300)

```

## Age of Maximal GBC 

```{r echo=FALSE}

names(gam.agepeaks.glasser)[2] <- "region"
 
right_gam.agepeaks.glasser <-  gam.agepeaks.glasser
right_gam.agepeaks.glasser$region<- gsub(x = gam.agepeaks.glasser$region, pattern = "R_", replacement = "")
right_gam.agepeaks.glasser$region <-  gsub(x = right_gam.agepeaks.glasser$region, pattern = "_ROI", replacement = "")
right_gam.agepeaks.glasser <- right_gam.agepeaks.glasser[-which(grepl("L_", right_gam.agepeaks.glasser$region)),]

#ggseg(.data = right_gam.agepeaks.glasser, atlas = "glasser", mapping=aes(fill=age.peak), position = c("stacked")) + theme_void() + scale_fill_gradientn(colors = viridis_pal(option="B")(10))

left_gam.agepeaks.glasser <-  gam.agepeaks.glasser
left_gam.agepeaks.glasser$region<- gsub(x = gam.agepeaks.glasser$region, pattern = "L_", replacement = "")
left_gam.agepeaks.glasser$region <-  gsub(x = left_gam.agepeaks.glasser$region, pattern = "_ROI", replacement = "")
left_gam.agepeaks.glasser <- left_gam.agepeaks.glasser[-which(grepl("R_", left_gam.agepeaks.glasser$region)),]
 
 
 
(glasser_agepeakR <- ggplot() + geom_brain(data=right_gam.agepeaks.glasser, 
                      atlas=glasser, 
                      mapping=aes(fill=age.peak), 
                      show.legend=TRUE, 
                      hemi = "right") + 
  scale_fill_gradientn(colors = viridis_pal(option="B")(10)) + theme_void())
#ggsave(glasser_agepeakR, file="/cbica/projects/network_replication/adapted_Rscripts/Figures/Glasser/GBC/glasser_agepeakR.pdf", width = 6, height=4, dpi=300)


(glasser_agepeakL <- ggplot() + geom_brain(data=left_gam.agepeaks.glasser, 
                      atlas=glasser, 
                      mapping=aes(fill=age.peak), 
                      show.legend=TRUE, 
                      hemi = "left") + 
  scale_fill_gradientn(colors = viridis_pal(option="B")(10)) + theme_void())
#ggsave(glasser_agepeakL, file="/cbica/projects/network_replication/adapted_Rscripts/Figures/Glasser/GBC/glasser_agepeakL.pdf", width = 6, height=4, dpi=300)
```
