---
title: "Spin Test Parcel Rotation Matrix"
author: "Audrey Luo"
date: "2023-12-01"
output: html_document
---

This Rmd file using rotate_parcellation to generate 10k rotated permutations of a parcellation, given the coordinates of left and right hemispheres of this parcellation on the sphere.

The output is a vector of 1:Number_of_parcels for each permutation which tries to conserve the relative position of each parcel

- Schaefer .annot files were downloaded from: https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/FreeSurfer5.3/fsaverage/label
 

```{r setup}
# rotate.parcellation.R and perm.sphere.p.R are downloaded from https://github.com/frantisekvasa/rotate_parcellation
source("/cbica/projects/network_replication/software/rotate.parcellation.R")
source("/cbica/projects/network_replication/software/perm.sphere.p.R")
library(freesurfer)
library(magrittr)
library(dplyr)
library(freesurferformats)
```

 

```{r schaefer200x7}
schaefer200.coords <- read.csv("/cbica/projects/network_replication/software/rotate_parcellation/MNI_coords/Schaefer2018_200Parcels_7Networks_order_FSLMNI152_1mm.Centroid_RAS_reordered.csv") #coordinates of schaefer200.coords parcel centroids in MNI (made from 2_parcelLabels.Rmd) 
 
lh.schaefer.annot <- read_annotation(sprintf("/cbica/projects/network_replication/software/rotate_parcellation/annot/lh.Schaefer2018_%1$sParcels_%2$sNetworks_order.annot", 200, 7))
rh.schaefer.annot <- read_annotation(sprintf("/cbica/projects/network_replication/software/rotate_parcellation/annot/rh.Schaefer2018_%1$sParcels_%2$sNetworks_order.annot", 200, 7))

label <- data.frame(c(lh.schaefer.annot$colortable[2:101,1], rh.schaefer.annot$colortable[2:101,1])) %>% setNames("ROI.Name")
schaefer200.coords <- left_join(schaefer200.coords, label, by="ROI.Name")
 
 

perm.id.full <- rotate.parcellation(coord.l = as.matrix(schaefer200.coords[1:100,4:6]), coord.r = as.matrix(schaefer200.coords[101:200,4:6]), nrot = 10000) #rotate the schaefer200.coords parcellation 10,000 times on the freesurfer sphere to generate spatial nulls for spin-based permutation significance testing 
  
saveRDS(perm.id.full, "/cbica/projects/network_replication/software/rotate_parcellation/schaefer200x7.coords_sphericalrotations_N10k.rds")
 

```
 

