---
title: "CovBat harmonization"
author: "Audrey Luo"
date: "2023-11-15"
output: html_document
---

# Perform CovBat Harmonization on Connectivity Metrics (GBC, BNC, WNC)
Covbat for GBC, BNC, and WNC can be performed locally using this Rmd file.
```{r setup_covbat, include=FALSE}
#install.packages("/cbica/projects/network_replication/software/covBat_gam/ComBatFamily_0.1.0.tar.gz", repos=NULL, type='source')
library(ComBatFamily)
library(dplyr)
library(mgcv)

dataset <- "HBN"
dir <- sprintf("/cbica/projects/network_replication/revisions/output/%1$s/GBC/", dataset)
  
```


```{r load_subxparcel}
participants <- read.csv("/cbica/projects/network_replication/input/HBN/sample_selection/HBN_demographics_finalsample_20230629.csv")
 

#GBC - loads GBC_subxparcel_schaefer200 absvalue and thresholded
GBC_subxparcel_schaefer200_absvalue <- read.csv(paste0(dir, "GBC_subxparcel_matrix_schaefer200_absvalue.csv"))
GBC_subxparcel_schaefer200_absvalue <- GBC_subxparcel_schaefer200_absvalue[,-1]
GBC_subxparcel_schaefer200_thresholded <- read.csv(paste0(dir, "GBC_subxparcel_matrix_schaefer200_thresholded.csv"))
GBC_subxparcel_schaefer200_thresholded <- GBC_subxparcel_schaefer200_thresholded[,-1]
 
row.names(GBC_subxparcel_schaefer200_absvalue) <- participants$sub
row.names(GBC_subxparcel_schaefer200_thresholded) <- participants$sub
```


```{r run_covbat}
age_vec <- participants$age 
sex_vec <- as.factor(participants$sex)
 
meanFD_avgSes_vec <- participants$meanFD_avgSes
 
covar_df <- bind_cols(participants$sub, as.numeric(age_vec), as.factor(sex_vec), as.numeric(meanFD_avgSes_vec))
covar_df <- dplyr::rename(covar_df, sub=...1,
                          age = ...2,
                          sex = ...3,
                          meanFD_avgSes = ...4)
 
# Harmonize GBC 
data.harmonized_GBC <- lapply(list(GBC_subxparcel_schaefer200_absvalue, GBC_subxparcel_schaefer200_thresholded), covfam, bat = as.factor(participants$ses), covar = covar_df, gam, y ~ s(age, k=3, fx=T) + as.factor(sex) + as.numeric(meanFD_avgSes))
names(data.harmonized_GBC) <- c("absvalue", "thresholded")
#cor(c(as.matrix(data.harmonized_GBC$absvalue$dat.covbat)), c(as.matrix(GBC_subxparcel_schaefer200_absvalue)))
```


```{r save_out}

#GBC - save out covbat harmonized connectivity metrics 
write.csv(data.harmonized_GBC$absvalue$dat.covbat, paste0(dir, sprintf("GBC_subxparcel_matrix_schaefer200_absvalue_covbat.csv")))
write.csv(data.harmonized_GBC$thresholded$dat.covbat, paste0(dir, sprintf("GBC_subxparcel_matrix_schaefer200_thresholded_covbat.csv")))

```

 

 
