---
title: "Region and Participant Lists (all atlases)"
author: "Audrey Luo"
date: "3/25/2022"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 5
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ciftiTools)
ciftiTools.setOption('wb_path', '/Applications/workbench/')
library(gifti)
library(cifti)
library(dplyr)
```


make region lists
```{r}
glasser_pconn <- read_cifti("/cbica/projects/network_replication/pconn/sub-4238772277/sub-4238772277_ses-PNC1_task-rest_acq-singleband_space-fsLR_atlas-Glasser_den-91k_den-91k_bold.pconn.nii")
#write.csv(names(glasser_pconn$Parcel), "/cbica/projects/network_replication/atlases/parcellations/glasser360_regionlist.csv")
names(glasser_pconn$Parcel)


gordon_pconn <- read_cifti("/cbica/projects/network_replication/pconn/sub-1786758517/sub-1786758517_ses-PNC1_task-rest_acq-singleband_space-fsLR_atlas-Gordon_den-91k_den-91k_bold.pconn.nii")
#write.csv(names(gordon_pconn$Parcel), "/cbica/projects/network_replication/atlases/parcellations/gordon_regionlist.csv")
 
schaefer200_17Net_pconn <- read_cifti("/cbica/projects/network_replication/pconn/sub-3607981599/sub-3607981599_ses-PNC1_task-rest_acq-singleband_space-fsLR_atlas-Schaefer217_den-91k_den-91k_bold.pconn.nii")
#write.csv(names(schaefer200_17Net_pconn$Parcel), "/cbica/projects/network_replication/atlases/parcellations/schaefer200x17_regionlist.csv")
names(schaefer200_pconn$Parcel)

schaefer400_17Net_pconn <- read_cifti("/cbica/projects/network_replication/pconn/sub-3607981599/sub-3607981599_ses-PNC1_task-rest_acq-singleband_space-fsLR_atlas-Schaefer417_den-91k_den-91k_bold.pconn.nii")
#write.csv(names(schaefer400_17Net_pconn$Parcel), "/cbica/projects/network_replication/atlases/parcellations/schaefer400x17_regionlist.csv")

# regions lists for Schaefer 200 and 400 7 Network parcellation from xcp github - https://github.com/PennLINC/xcpEngine/tree/master/atlas
```


load region lists as variables
```{r}

schaefer400.17Net.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/schaefer400x17_regionlist.csv", header = T)
names(schaefer400.17Net.parcel.labels)[2] <- "labels"
schaefer200.17Net.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/schaefer200x17_regionlist.csv", header = T)
names(schaefer200.17Net.parcel.labels)[2] <- "labels"

schaefer400.7Net.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/schaefer400_7Network_regionlist.csv", header = T)
names(schaefer400.7Net.parcel.labels)[2] <- "labels"
schaefer200.7Net.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/schaefer200_7Network_regionlist.csv", header = T)
names(schaefer200.7Net.parcel.labels)[2] <- "labels"


glasser.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/glasser360_regionlist.csv", header = T)
names(glasser.parcel.labels)[2] <- "labels"
gordon.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/gordon_regionlist.csv", header = T)
names(gordon.parcel.labels)[2] <- "labels"

```

participant list
```{r}
#list of RBC-PNC ids with processed rest-task_acq-singleband data to compute GBC on
participants.RBC <- read.csv("/cbica/projects/network_replication/PNC/bblid_scanid_sub.csv", header=T) # not sure if this is the right participant list since the subject #'s in pconn are not identical to this list!
participants.RBC$rbcid <- paste("sub", participants.RBC$rbcid, sep="-")
participants.adam <- read.table("/cbica/projects/network_replication/PNC/participants.txt", header=F)
names(participants.adam) <- "scanid"

pconn.participants <- read.csv("/cbica/projects/network_replication/adapted_Rscripts/pconn_participants.csv")
pconn.participants <- as.data.frame(pconn.participants[,-c(which(names(pconn.participants) == c("X.1","X")))])
names(pconn.participants) <- "rbcid"
#to_exclude <- setdiff(as.character(participants.RBC$rbcid), as.character(pconn.participants$rbcid)) #these are the participants that are in Adam's list but not in my pconn directory. so need to exclude these

#get the row indices to remove from 'participants' df
#y <- c()
#for(i in 1:length(to_exclude)){
#  x <- which(participants.RBC$rbcid == to_exclude[i])
#  y <- append(y, x)
#}
#participants_rbcid.scanid <- participants.RBC[-y, ]

participants <- merge(participants.adam, participants.RBC, by="scanid")

#write.csv(participants, '/cbica/projects/network_replication/adapted_Rscripts/participants_allIDs.csv')
 
```



there are 185 subjects in `/cbica/projects/network_replications/pconn` who are missing files-as expected
```{r}

# need to go through each folder and see if file exists
rbcid <- as.character(pconn.participants$rbcid)
subs_no_files <- c()
for(i in 1:length(rbcid)){
  temp_id <- rbcid[i]
  if(!file.exists(sprintf("/cbica/projects/network_replication/pconn/%1$s/%1$s_ses-PNC1_task-rest_acq-singleband_space-fsLR_atlas-Schaefer217_den-91k_den-91k_bold.pconn.nii",temp_id))){
  print(temp_id)
    subs_no_files <- append(subs_no_files, temp_id)}
}
length(subs_no_files) #185 subjects have empty folders
#write.csv(subs_no_files, 'subs_no_files.csv')
 
intersect(subs_no_files, participants$rbcid) #10
 
```


