---
title: "Parcellate SNR masks (all atlases)"
author: "Audrey"
date: "12/13/2021"
output: html_document
--- 

Parcellate SNR masks
```{r}

library(cifti)
library(ciftiTools)
ciftiTools.setOption('wb_path', '/Applications/workbench/')
library(gifti)
 
#Parcellate SNR masks
##glasser
command1 = "-cifti-parcellate /cbica/projects/network_replication/atlases/Masks/SNRmask_fslr.dscalar.nii /cbica/projects/network_replication/atlases/dlabel/glasser_space-fsLR_den-32k_desc-atlas.dlabel.nii COLUMN /cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_glasser360.pscalar.nii" # SNRmask_glasser360.pscalar.nii is the output (parcellated SNR mask based on the SNRmask from Zaixu and the atlas)
ciftiTools::run_wb_cmd(command1, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)

##schaefer400x7
command2 = "-cifti-parcellate /cbica/projects/network_replication/atlases/Masks/SNRmask_fslr.dscalar.nii /cbica/projects/network_replication/atlases/dlabel/Schaefer2018_400Parcels_7Networks_order.dlabel.nii COLUMN /cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_schaefer400x7.pscalar.nii"
ciftiTools::run_wb_cmd(command2, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)

##schaefer400x17
command3 = "-cifti-parcellate /cbica/projects/network_replication/atlases/Masks/SNRmask_fslr.dscalar.nii /cbica/projects/network_replication/atlases/dlabel/Schaefer2018_400Parcels_17Networks_order.dlabel.nii COLUMN /cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_schaefer400x17.pscalar.nii"
ciftiTools::run_wb_cmd(command3, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)
## hopefully schaefer_space-fsLR_den-32k_desc-400Parcels17Networks_atlas.dlabel.nii = Schaefer2018_400Parcels_17Networks_order.dlabel.nii


##schaefer200x7
command4 = "-cifti-parcellate /cbica/projects/network_replication/atlases/Masks/SNRmask_fslr.dscalar.nii /cbica/projects/network_replication/atlases/dlabel/Schaefer2018_200Parcels_7Networks_order.dlabel.nii COLUMN /cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_schaefer200x7.pscalar.nii"
ciftiTools::run_wb_cmd(command4, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)

##schaefer200x17
command5 = "-cifti-parcellate /cbica/projects/network_replication/atlases/Masks/SNRmask_fslr.dscalar.nii /cbica/projects/network_replication/atlases/dlabel/Schaefer2018_200Parcels_17Networks_order.dlabel.nii COLUMN /cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_schaefer200x17.pscalar.nii"
ciftiTools::run_wb_cmd(command5, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)

##gordon
command6 = "-cifti-parcellate /cbica/projects/network_replication/atlases/Masks/SNRmask_fslr.dscalar.nii /cbica/projects/network_replication/atlases/dlabel/gordon_space-fsLR_den-32k_desc-atlas.dlabel.nii COLUMN /cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_gordon.pscalar.nii"
ciftiTools::run_wb_cmd(command6, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)

 
```



Read in parcellated SNR masks, threshold at 75% of vertices, and save parcel mask csvs
```{r}
#Read in parcellated SNR masks, threshold at 75% of vertices, and save parcel mask csvs
SNR.mask.glasser <- cifti::read_cifti("/cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_glasser360.pscalar.nii")
SNR.mask.glasser <- as.data.frame(SNR.mask.glasser$data)
colnames(SNR.mask.glasser) <- c("SNR.mask")
glasser.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/glasser360_regionlist.csv", header = T)
SNR.mask.glasser$label <- glasser.parcel.labels$label
SNR.mask.glasser$SNR.mask[SNR.mask.glasser$SNR.mask <= 0.75] <- 0
SNR.mask.glasser$SNR.mask[SNR.mask.glasser$SNR.mask > 0.75] <- 1
sum(SNR.mask.glasser$SNR.mask == 0) #24 glasser parcels removed from analysis
#write.csv(SNR.mask.glasser, "/cbica/projects/network_replication/atlases/Masks/SNRmask_glasser360.csv", quote = F, row.names = F)

SNR.mask.schaefer400x17<- cifti::read_cifti("/cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_schaefer400x17.pscalar.nii")
SNR.mask.schaefer400x17<- as.data.frame(SNR.mask.schaefer400x17$data)
colnames(SNR.mask.schaefer400x17) <- c("SNR.mask")
schaefer.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/schaefer400x17_regionlist.csv", header = T)
SNR.mask.schaefer400x17$label <- schaefer.parcel.labels$label
SNR.mask.schaefer400x17$SNR.mask[SNR.mask.schaefer400x17$SNR.mask <= 0.75] <- 0
SNR.mask.schaefer400x17$SNR.mask[SNR.mask.schaefer400x17$SNR.mask > 0.75] <- 1
sum(SNR.mask.schaefer400x17$SNR.mask == 0) #24 schaefer400 parcels removed from analysis
#write.csv(SNR.mask.schaefer400x17, "/cbica/projects/network_replication/atlases/Masks/SNRmask_schaefer400x17.csv", quote = F, row.names = F)
 

SNR.mask.schaefer400x7<- cifti::read_cifti("/cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_schaefer400x7.pscalar.nii")
SNR.mask.schaefer400x7<- as.data.frame(SNR.mask.schaefer400x7$data)
colnames(SNR.mask.schaefer400x7) <- c("SNR.mask")
schaefer.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/schaefer400_7Network_ggseg_regionlist.csv", header = T)
SNR.mask.schaefer400x7$label <- schaefer.parcel.labels$label
SNR.mask.schaefer400x7$SNR.mask[SNR.mask.schaefer400x7$SNR.mask <= 0.75] <- 0
SNR.mask.schaefer400x7$SNR.mask[SNR.mask.schaefer400x7$SNR.mask > 0.75] <- 1
sum(SNR.mask.schaefer400x7$SNR.mask == 0) #24 schaefer400 parcels removed from analysis
#write.csv(SNR.mask.schaefer400x7, "/cbica/projects/network_replication/atlases/Masks/SNRmask_schaefer400x7.csv", quote = F, row.names = F)
 
SNR.mask.schaefer200x17<- cifti::read_cifti("/cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_schaefer200x17.pscalar.nii")
SNR.mask.schaefer200x17<- as.data.frame(SNR.mask.schaefer200x17$data)
colnames(SNR.mask.schaefer200x17) <- c("SNR.mask")
schaefer.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/schaefer200x17_regionlist.csv", header = T)
SNR.mask.schaefer200x17$label <- schaefer.parcel.labels$label
SNR.mask.schaefer200x17$SNR.mask[SNR.mask.schaefer200x17$SNR.mask <= 0.75] <- 0
SNR.mask.schaefer200x17$SNR.mask[SNR.mask.schaefer200x17$SNR.mask > 0.75] <- 1
sum(SNR.mask.schaefer200x17$SNR.mask == 0) #11 schaefer200 parcels removed from analysis
#write.csv(SNR.mask.schaefer200x17, "/cbica/projects/network_replication/atlases/Masks/SNRmask_schaefer200x17.csv", quote = F, row.names = F)


SNR.mask.schaefer200x7<- cifti::read_cifti("/cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_schaefer200x7.pscalar.nii")
SNR.mask.schaefer200x7<- as.data.frame(SNR.mask.schaefer200x7$data)
colnames(SNR.mask.schaefer200x7) <- c("SNR.mask")
schaefer.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/schaefer200_7Network_ggseg_regionlist.csv", header = T)
SNR.mask.schaefer200x7$label <- schaefer.parcel.labels$label
SNR.mask.schaefer200x7$SNR.mask[SNR.mask.schaefer200x7$SNR.mask <= 0.75] <- 0
SNR.mask.schaefer200x7$SNR.mask[SNR.mask.schaefer200x7$SNR.mask > 0.75] <- 1
sum(SNR.mask.schaefer200x7$SNR.mask == 0) #11 schaefer200 parcels removed from analysis
#write.csv(SNR.mask.schaefer200x7, "/cbica/projects/network_replication/atlases/Masks/SNRmask_schaefer200x7.csv", quote = F, row.names = F)


SNR.mask.gordon <- cifti::read_cifti("/cbica/projects/network_replication/atlases/parcellations/surface/SNRmask_gordon.pscalar.nii")
SNR.mask.gordon <- as.data.frame(SNR.mask.gordon$data)
colnames(SNR.mask.gordon) <- c("SNR.mask")
gordon.parcel.labels <- read.csv("/cbica/projects/network_replication/atlases/parcellations/gordon_regionlist.csv", header = T)
SNR.mask.gordon$label <- gordon.parcel.labels$label
SNR.mask.gordon$SNR.mask[SNR.mask.gordon$SNR.mask <= 0.75] <- 0
SNR.mask.gordon$SNR.mask[SNR.mask.gordon$SNR.mask > 0.75] <- 1
sum(SNR.mask.gordon$SNR.mask == 0) #29 gordon parcels removed from analysis
#write.csv(SNR.mask.gordon, "/cbica/projects/network_replication/atlases/Masks/SNRmask_gordon.csv", quote = F, row.names = F)


```

```{r}

schaefer400x17 <- info_cifti('/cbica/projects/network_replication/atlases/dlabel/Schaefer2018_400Parcels_17Networks_order.dlabel.nii')
schaefer400x7 <- info_cifti('/cbica/projects/network_replication/atlases/dlabel/Schaefer2018_400Parcels_7Networks_order.dlabel.nii')

schaefer400x17$cifti
schaefer400x7$cifti

```

 