---
title: "Parcellate Sensorimotor-Association Axis for Glasser, Schaefer200 and 400 (7 and 17 Network), and Gordon"
author: "Valerie Jill Sydnor"
output: 
  html_document:
    theme: flatly
---
 
```{r setup, include=FALSE}
library(ciftiTools)
ciftiTools.setOption('wb_path', '/Applications/workbench/')
library(cifti)
#setwd("/cbica/projects/network_replication/")
```

**Script to parcellate the fslr/cifti Sensorimotor-Association Axis with commonly used cortical atlases**

GLASSER360 Multimodal Parcellation

```{r}
setwd("/cbica/projects/network_replication/")
command=sprintf("-cifti-parcellate ./dropbox/S-A_ArchetypalAxis/FSLRVertex/SensorimotorAssociation_Axis.dscalar.nii ./atlases/dlabel/glasser_space-fsLR_den-32k_desc-atlas.dlabel.nii COLUMN ./SAaxis/SensorimotorAssociation_Axis_parcellated/SensorimotorAssociation.Axis.Glasser360.pscalar.nii")
ciftiTools::run_wb_cmd(command, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)
```

SCHAEFER400 17 NETWORK Parcellation

```{r}
setwd("/cbica/projects/network_replication/")
command=sprintf("-cifti-parcellate ./dropbox/S-A_ArchetypalAxis/FSLRVertex/SensorimotorAssociation_Axis.dscalar.nii ./atlases/dlabel/Schaefer2018_400Parcels_17Networks_order.dlabel.nii COLUMN ./SAaxis/SensorimotorAssociation_Axis_parcellated/SensorimotorAssociation.Axis.Schaefer400.17Networks.pscalar.nii")
ciftiTools::run_wb_cmd(command, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)
```


SCHAEFER400 7 NETWORK Parcellation

```{r}
setwd("/cbica/projects/network_replication/")
command=sprintf("-cifti-parcellate ./dropbox/S-A_ArchetypalAxis/FSLRVertex/SensorimotorAssociation_Axis.dscalar.nii ./atlases/dlabel/Schaefer2018_400Parcels_7Networks_order.dlabel.nii COLUMN ./SAaxis/SensorimotorAssociation_Axis_parcellated/SensorimotorAssociation.Axis.Schaefer400.7Networks.pscalar.nii")
ciftiTools::run_wb_cmd(command, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)
```

SCHAEFER200 17 NETWORK Parcellation

```{r}
setwd("/cbica/projects/network_replication/")

command=sprintf("-cifti-parcellate ./dropbox/S-A_ArchetypalAxis/FSLRVertex/SensorimotorAssociation_Axis.dscalar.nii ./atlases/dlabel/Schaefer2018_200Parcels_17Networks_order.dlabel.nii COLUMN ./SAaxis/SensorimotorAssociation_Axis_parcellated/SensorimotorAssociation.Axis.Schaefer200.17Networks.pscalar.nii")
ciftiTools::run_wb_cmd(command, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)
```


SCHAEFER200 7 NETWORK Parcellation

```{r}
setwd("/cbica/projects/network_replication/")

command=sprintf("-cifti-parcellate ./dropbox/S-A_ArchetypalAxis/FSLRVertex/SensorimotorAssociation_Axis.dscalar.nii ./atlases/dlabel/Schaefer2018_200Parcels_7Networks_order.dlabel.nii COLUMN ./SAaxis/SensorimotorAssociation_Axis_parcellated/SensorimotorAssociation.Axis.Schaefer200.7Networks.pscalar.nii")
ciftiTools::run_wb_cmd(command, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)
```

GORDON333 Parcellation

```{r}

setwd("/cbica/projects/network_replication/")
command=sprintf("-cifti-parcellate ./dropbox/S-A_ArchetypalAxis/FSLRVertex/SensorimotorAssociation_Axis.dscalar.nii ./atlases/dlabel/gordon_space-fsLR_den-32k_desc-atlas.dlabel.nii COLUMN ./SAaxis/SensorimotorAssociation_Axis_parcellated/SensorimotorAssociation.Axis.Gordon333.pscalar.nii")
ciftiTools::run_wb_cmd(command, intern = FALSE, ignore.stdout = NULL, ignore.stderr = NULL)
```

