---
title: "HCPD Compute Functional Connectivity Metrics"
author: "Audrey Luo"
output: html_document
---


```{r setup, include=FALSE}

library(dplyr)
#source("/cbica/projects/network_replication/adapted_Rscripts/computeConnectivityMetrics.R")
dataset="HCPD"
knitr::opts_chunk$set(include = FALSE, eval = TRUE, echo = FALSE, warning = FALSE, message = FALSE) 
```


```{r loadParticipants}
# load participants
 
participants <- read.csv("/cbica/projects/network_replication/input/HCPD/sample_selection/HCPD_demographics_finalsample_20221226.csv")
participants <- gsub("HCD", "sub-", participants$src_subject_id)
 
```



```{r computeGBC}
# make output dfs: 
## GBC.subxparcel.matrix.glasser, GBC.subxparcel.matrix.gordon, GBC.subxparcel.matrix.schaefer200, GBC.subxparcel.matrix.schaefer400
atlases <- c("glasser", "gordon", "schaefer200", "schaefer400")
metric = "GBC"

for(i in c(1:length(atlases))){
  df_name <- paste0(metric, ".subxparcel.matrix.", atlases[i])
  assign(df_name, make_output_dfs(participants, atlases[i]))
}
  
 
# compute GBC
for(sub in c(1:length(participants))){
  for(i in c(1:length(atlases))){
    subjectID=as.character(participants[sub])
    HCPDid.data <- computeGBC(subjectID, atlases[i], "HCPD")
    dataname <- sprintf("%s.%s.%s", metric, "subxparcel.matrix", atlases[i]) 
    df_toUpdate <- get(dataname)
    df_toUpdate[sub,] <- cbind(subjectID, t(HCPDid.data)) #update the name of the df every iteration to GBC.subxparcel.matrix.[atlas]
    assign(dataname, df_toUpdate)  
    print(paste(sub, "/", length(participants), "-", subjectID, atlases[i]))
  }
}
 
write.csv(GBC.subxparcel.matrix.glasser, "/cbica/projects/network_replication/output/HCPD/GBC/GBC_subxparcel_matrix_glasser.csv", row.names=F, quote=F)
write.csv(GBC.subxparcel.matrix.gordon, "/cbica/projects/network_replication/output/HCPD/GBC/GBC_subxparcel_matrix_gordon.csv", row.names=F, quote=F)
write.csv(GBC.subxparcel.matrix.schaefer200, "/cbica/projects/network_replication/output/HCPD/GBC/GBC_subxparcel_matrix_schaefer200.csv", row.names=F, quote=F)
write.csv(GBC.subxparcel.matrix.schaefer400, "/cbica/projects/network_replication/output/HCPD/GBC/GBC_subxparcel_matrix_schaefer400.csv", row.names=F, quote=F)
   
```



```{r computeBNC}
# make output dfs: 
## BNC.subxparcel.matrix.gordon, BNC.subxparcel.matrix.schaefer200x7, BNC.subxparcel.matrix.schaefer400x7
atlases <- c("gordon", "schaefer200x7", "schaefer200x17", "schaefer400x7", "schaefer400x17")

metric = "BNC"

for(i in c(1:length(atlases))){
  df_name <- paste0(metric, ".subxparcel.matrix.", atlases[i])
  assign(df_name, make_output_dfs(participants, atlases[i]))
}


# compute BNC
for(sub in c(1:length(participants))){
  for(i in c(1:length(atlases))){
    subjectID=as.character(participants[sub])
    print(paste(subjectID, atlases[i], metric, dataset))
    id.data <- computeBNC_WNC(subjectID, atlases[i], metric, dataset)
    
    dataname <- sprintf("%s.%s.%s", metric, "subxparcel.matrix", atlases[i]) 
    df_toUpdate <- get(dataname)
    df_toUpdate[sub,] <- cbind(subjectID, t(id.data)) #update the name of the df every iteration to BNC.subxparcel.matrix.[atlas]
    assign(dataname, df_toUpdate)  
    print(paste(sub, "/", length(participants), "-", subjectID, atlases[i]))
  }
}

  
write.csv(BNC.subxparcel.matrix.gordon, "/cbica/projects/network_replication/output/HCPD/BNC/BNC_subxparcel_matrix_gordon.csv", row.names=F, quote=F)
write.csv(BNC.subxparcel.matrix.schaefer200x7, "/cbica/projects/network_replication/output/HCPD/BNC/BNC_subxparcel_matrix_schaefer200x7.csv", row.names=F, quote=F)
write.csv(BNC.subxparcel.matrix.schaefer400x7, "/cbica/projects/network_replication/output/HCPD/BNC/BNC_subxparcel_matrix_schaefer400x7.csv", row.names=F, quote=F)
write.csv(BNC.subxparcel.matrix.schaefer200x17, "/cbica/projects/network_replication/output/HCPD/BNC/BNC_subxparcel_matrix_schaefer200x17.csv", row.names=F, quote=F)
write.csv(BNC.subxparcel.matrix.schaefer400x17, "/cbica/projects/network_replication/output/HCPD/BNC/BNC_subxparcel_matrix_schaefer400x17.csv", row.names=F, quote=F)
 

```
 
 

```{r computeWNC}

# make output dfs: 
## WNC.subxparcel.matrix.gordon, WNC.subxparcel.matrix.schaefer200x7, WNC.subxparcel.matrix.schaefer400x7
atlases <- c("gordon", "schaefer200x7", "schaefer200x17", "schaefer400x7", "schaefer400x17")
 
metric = "WNC"

for(i in c(1:length(atlases))){
  df_name <- paste0(metric, ".subxparcel.matrix.", atlases[i])
  assign(df_name, make_output_dfs(participants, atlases[i]))
}


# compute WNC
for(sub in c(1:length(participants))){
  for(i in c(1:length(atlases))){
    subjectID=as.character(participants[sub])
    print(paste(subjectID, atlases[i], metric, dataset))
    id.data <- computeBNC_WNC(subjectID, atlases[i], metric, dataset)
    
    dataname <- sprintf("%s.%s.%s", metric, "subxparcel.matrix", atlases[i]) 
    df_toUpdate <- get(dataname)
    df_toUpdate[sub,] <- cbind(subjectID, t(id.data)) #update the name of the df every iteration to BNC.subxparcel.matrix.[atlas]
    assign(dataname, df_toUpdate)  
    print(paste(sub, "/", length(participants), "-", subjectID, atlases[i]))
  }
}

write.csv(WNC.subxparcel.matrix.gordon, "/cbica/projects/network_replication/output/HCPD/WNC/WNC_subxparcel_matrix_gordon.csv", row.names=F, quote=F)
write.csv(WNC.subxparcel.matrix.schaefer200x7, "/cbica/projects/network_replication/output/HCPD/WNC/WNC_subxparcel_matrix_schaefer200x7.csv", row.names=F, quote=F)
write.csv(WNC.subxparcel.matrix.schaefer400x7, "/cbica/projects/network_replication/output/HCPD/WNC/WNC_subxparcel_matrix_schaefer400x7.csv", row.names=F, quote=F)
write.csv(WNC.subxparcel.matrix.schaefer200x17, "/cbica/projects/network_replication/output/HCPD/WNC/WNC_subxparcel_matrix_schaefer200x17.csv", row.names=F, quote=F)
write.csv(WNC.subxparcel.matrix.schaefer400x17, "/cbica/projects/network_replication/output/HCPD/WNC/WNC_subxparcel_matrix_schaefer400x17.csv", row.names=F, quote=F)
 

```


# Extract edge-level data (parcel-to-parcel connectivity)
```{r edge_level_dfs}

  
# make a dataframe in which rows are subjects, and columns are the names of the edges (parcel1_to_parcel2)
# the entries represent the parcel-by-parcel correlation
 

# gordon
# for each subject, turn the connectivity matrix into a vector
extractEdge.gordon <- lapply(participants, extractParcel2ParcelConn, "gordon", "HCPD")
extractEdge.glasser <- lapply(participants, extractParcel2ParcelConn, "glasser", "HCPD")
extractEdge.schaefer200x7 <- lapply(participants, extractParcel2ParcelConn, "schaefer200x7", "HCPD")
extractEdge.schaefer200x17 <- lapply(participants, extractParcel2ParcelConn, "schaefer200x17", "HCPD")
extractEdge.schaefer400x7 <- lapply(participants, extractParcel2ParcelConn, "schaefer400x7", "HCPD")
extractEdge.schaefer400x17 <- lapply(participants, extractParcel2ParcelConn, "schaefer400x17", "HCPD")

 
# for other atlases -- need to run this next
atlases <- c("glasser", "gordon", "schaefer200x7", "schaefer200x17", "schaefer400x7", "schaefer400x17")
atlases <- c("glasser", "schaefer200x7", "schaefer200x17", "schaefer400x7", "schaefer400x17")
for(i in c(1:length(atlases))){
  extractEdge <- get(paste0("extractEdge.", atlases[i]))
  names(extractEdge) <- participants 
  columns_extractEdge <- bind_rows(extractEdge) # turn list into a dataframe
  subxedge <- as.data.frame(t(columns_extractEdge)) # transpose dataframe
  
  edge <- read.csv(sprintf("/cbica/projects/network_replication/atlases/edge/%1$s_edge.csv", atlases[i]))
  edge <- edge[,2]
  names(subxedge) <- edge # columns = names of edges
  
  subxedge <- subxedge %>% mutate(subject = rownames(subxedge))
  subxedge <- subxedge %>% relocate(subject)
  rownames(subxedge) <- NULL
  
  saveRDS(subxedge, sprintf("/cbica/projects/network_replication/output/HCPD/edge/subxedge_%1$s.RData", atlases[i])) 
  print(atlases[i])
} 
 


```




# Perform CovBat Harmonization on Connectivity Metrics (GBC, BNC, WNC)

```{r setup_covbat, include=FALSE}

#install.packages("/cbica/projects/network_replication/software/covBat_gam/ComBatFamily_0.1.0.tar.gz", repos=NULL, type='source')
library(ComBatFamily)
library(dplyr)
library(mgcv)

atlases_GBC <- c("glasser", "gordon", "schaefer200", "schaefer400")
atlases <- c("gordon", "schaefer200x7", "schaefer200x17", "schaefer400x7", "schaefer400x17")
dataset <- "HCPD"
  
```


# main analysis

```{r load_subxparcel}
participants <- read.csv("/cbica/projects/network_replication/input/HCPD/sample_selection/HCPD_demographics_finalsample_20221226.csv")
 
 
#GBC - loads GBC_subxparcel_glasser, GBC_subxparcel_gordon, GBC_subxparcel_schaefer200, GBC_subxparcel_schaefer400
metric = "GBC"
for(i in c(1:length(atlases_GBC))){
  df_name <- paste0(metric, "_", "subxparcel_", atlases_GBC[i])
  assign(df_name, read.csv(sprintf("/cbica/projects/network_replication/output/%1$s/%2$s/%2$s_subxparcel_matrix_%3$s.csv", dataset, metric, atlases_GBC[i])))
  assign(df_name, data.frame(get(df_name)[,-1]))
  #assign(row.names(get(df_name)), subjects)
  print(df_name)
} 
  
row.names(GBC_subxparcel_glasser) <- participants$sub
row.names(GBC_subxparcel_gordon) <- participants$sub
row.names(GBC_subxparcel_schaefer200) <- participants$sub
row.names(GBC_subxparcel_schaefer400) <- participants$sub
 

#BNC - loads BNC_subxparcel_gordon, BNC_subxparcel_schaefer200x7, BNC_subxparcel_schaefer200x17, BNC_subxparcel_schaefer400x7, BNC_subxparcel_schaefer400x17
metric = "BNC"
for(i in c(1:length(atlases))){
  df_name <- paste0(metric, "_", "subxparcel_", atlases[i])
  assign(df_name, read.csv(sprintf("/cbica/projects/network_replication/output/%1$s/%2$s/%2$s_subxparcel_matrix_%3$s.csv", dataset, metric, atlases[i])))
  assign(df_name, data.frame(get(df_name)[,-1]))
  print(df_name)
} 
  
row.names(BNC_subxparcel_gordon) <- participants$sub
row.names(BNC_subxparcel_schaefer200x7) <- participants$sub
row.names(BNC_subxparcel_schaefer200x17) <- participants$sub
row.names(BNC_subxparcel_schaefer400x7) <- participants$sub
row.names(BNC_subxparcel_schaefer400x17) <- participants$sub


#WNC - loads WNC_subxparcel_gordon, WNC_subxparcel_schaefer200x7,WNC_subxparcel_schaefer200x17, WNC_subxparcel_schaefer400x7, WNC_subxparcel_schaefer400x17
metric = "WNC"
for(i in c(1:length(atlases))){
  df_name <- paste0(metric, "_", "subxparcel_", atlases[i])
  assign(df_name, read.csv(sprintf("/cbica/projects/network_replication/output/%1$s/%2$s/%2$s_subxparcel_matrix_%3$s.csv", dataset, metric, atlases[i])))
  assign(df_name, data.frame(get(df_name)[,-1]))
  print(df_name)
} 
  
row.names(WNC_subxparcel_gordon) <- participants$sub
row.names(WNC_subxparcel_schaefer200x7) <- participants$sub
row.names(WNC_subxparcel_schaefer200x17) <- participants$sub
row.names(WNC_subxparcel_schaefer400x7) <- participants$sub
row.names(WNC_subxparcel_schaefer400x17) <- participants$sub

```


```{r run_covbat}

age_vec <- participants$interview_age/12
sex_vec <- as.factor(participants$sex)
meanFD_avgSes_vec <- participants$meanFD_avgSes

covar_df <- bind_cols(participants$sub, as.numeric(age_vec), as.factor(sex_vec), as.numeric(meanFD_avgSes_vec))
covar_df <- dplyr::rename(covar_df, sub=...1,
                          age = ...2,
                          sex = ...3,
                          meanFD_avgSes = ...4)
batch <- participants$site 
 
# Harmonize GBC
data.harmonized_GBC <- lapply(list(GBC_subxparcel_glasser, GBC_subxparcel_gordon, GBC_subxparcel_schaefer200, GBC_subxparcel_schaefer400), covfam, bat = as.factor(participants$site), covar = covar_df, gam, y ~ s(age, k=3, fx=T) + as.factor(sex) + meanFD_avgSes)
names(data.harmonized_GBC) <- atlases_GBC

# Harmonize BNC
data.harmonized_BNC <- lapply(list(BNC_subxparcel_gordon, BNC_subxparcel_schaefer200x7, BNC_subxparcel_schaefer200x17, BNC_subxparcel_schaefer400x7, BNC_subxparcel_schaefer400x17), covfam, bat = as.factor(participants$site), covar = covar_df, gam, y ~ s(age, k=3, fx=T) + as.factor(sex) + meanFD_avgSes)
names(data.harmonized_BNC) <- atlases 
 
# Harmonize WNC
data.harmonized_WNC <- lapply(list(WNC_subxparcel_gordon, WNC_subxparcel_schaefer200x7, WNC_subxparcel_schaefer200x17, WNC_subxparcel_schaefer400x7, WNC_subxparcel_schaefer400x17), covfam, bat = as.factor(participants$site), covar = covar_df, gam, y ~ s(age, k=3, fx=T) + as.factor(sex) + meanFD_avgSes)
names(data.harmonized_WNC) <- atlases 


```


```{r save_out}

#GBC - save out covbat harmonized connectivity metrics 
metric = "GBC"
for(i in c(1:length(atlases_GBC))){
  df_name <- paste0(metric, "_", "subxparcel_", atlases_GBC[i], "_covbat")
  assign(df_name, data.frame(data.harmonized_GBC[[atlases_GBC[i]]]$dat.covbat))
  write.csv(get(df_name), sprintf("/cbica/projects/network_replication/output/%1$s/%2$s/%2$s_subxparcel_matrix_%3$s_covbat.csv", dataset, metric, atlases_GBC[i]))
  print(df_name)
}  

 
#BNC - save out covbat harmonized connectivity metrics 
metric = "BNC"
for(i in c(1:length(atlases))){
  df_name <- paste0(metric, "_", "subxparcel_", atlases[i], "_covbat")
  assign(df_name, data.frame(data.harmonized_BNC[[atlases[i]]]$dat.covbat))
  write.csv(get(df_name), sprintf("/cbica/projects/network_replication/output/%1$s/%2$s/%2$s_subxparcel_matrix_%3$s_covbat.csv", dataset, metric, atlases[i]))
  print(df_name)
}  


#WNC - save out covbat harmonized connectivity metrics 
metric = "WNC"
for(i in c(1:length(atlases))){
  df_name <- paste0(metric, "_", "subxparcel_", atlases[i], "_covbat")
  assign(df_name, data.frame(data.harmonized_WNC[[atlases[i]]]$dat.covbat))
  write.csv(get(df_name), sprintf("/cbica/projects/network_replication/output/%1$s/%2$s/%2$s_subxparcel_matrix_%3$s_covbat.csv", dataset, metric, atlases[i]))
  print(df_name)
}  
```

 


# Perform CovBat Harmonization on Edges
```{r edge_covbat}

# function for performing CovBat on connectivity metrics output for all atlases
apply_covbat_edge <- function(atlas, dataset) {
  subxedge <- readRDS(sprintf("/cbica/projects/network_replication/output/%1$s/edge/subxedge_%2$s.RData", dataset, atlas))
  print("Edge RData loaded")
  subxedge <- data.frame(subxedge[,-1])
  row.names(subxedge) <- subxedge$subject
  print("subxedge loaded")
  if(dataset=="HCPD") {
    participants <- read.csv("/cbica/projects/network_replication/input/HCPD/sample_selection/HCPD_demographics_finalsample_20221226.csv")
    participants <- participants[match(names(subxedge), participants$sub),]
    age_vec <- participants$interview_age/12
    sex_vec <- as.factor(participants$sex)
    meanFD_avgSes_vec <- participants$meanFD_avgSes
    batch <- participants$site
    
  } else if (dataset=="HBN") { 
    participants <- read.csv("/cbica/projects/network_replication/input/HBN/sample_selection/HBN_demographics_finalsample_202230223.csv")
    participants_noAge_index <- c(which(is.na(participants$age))) #age not collected on 58 participants 
    participants <- participants[-c(which(is.na(participants$age))),] 
    participants <- participants[-c(which(participants$sub=="sub-NDARCE721YB5"))]
    age_vec <- participants$age 
    sex_vec <- as.factor(participants$sex)
    meanFD_avgSes_vec <- participants$meanFD_avgSes
    batch <- participants$ses
    
  } else {
    print("provide proper participants df")
  }
  covar_df <- bind_cols(participants$sub, as.numeric(age_vec), as.factor(sex_vec), as.numeric(meanFD_avgSes_vec))
  covar_df <- dplyr::rename(covar_df, sub=...1,
                            age = ...2,
                            sex = ...3,
                            meanFD_avgSes = ...4)
  print("Harmonizing data")
  data.harmonized <- covfam(data=subxedge, bat = as.factor(batch), covar = covar_df, gam, y ~ s(age, k=3, fx=T) + as.factor(sex) + meanFD_avgSes)
  data.harmonized_covbat <- data.frame(data.harmonized$dat.covbat)
  print(paste(atlas, "edge", dataset, "done"))
  return(data.harmonized_covbat)
}


atlases <- c("gordon", "schaefer200x7", "schaefer200x17", "schaefer400x7", "schaefer400x17")

edge_harmonized <- lapply(atlases, apply_covbat_edge, dataset)
names(edge_harmonized) <- atlases

for(i in c(1:length(edge_harmonized))){
  saveRDS(edge_harmonized[[atlases[i]]], sprintf("/cbica/projects/network_replication/output/%1$s/edge/subxedge_%2$s_covbat.RData", dataset, atlases[i]))
  print(atlases[i])
} 
```

